Phil\MoneyBundle\Entity\DoctrineStorageRatio:
  type: entity
  table: phil_money_doctrine_storage_ratios
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    currencyCode:
      type: string
      column: currency_code
      length: 3
      nullable: false
      unique: true
    ratio:
      type: float
      column: ratio
      length: 255
      nullable: false
